@echo off
chcp 936 >nul
title Mod管理器注入工具
cd /d "%~dp0"

if not exist "index.html" (
  echo [!] 未找到 index.html，请把本工具放在游戏目录下运行。
  pause
  exit /b 1
)

:menu
cls
echo ========================================
echo   Mod管理器注入工具
echo ========================================
echo.
echo   1. 注入管理器
echo   2. 取消注入
echo   3. 退出
echo.
set "choice="
set /p choice=请选择 [1/2/3]: 
if "%choice%"=="1" goto inject
if "%choice%"=="2" goto remove
if "%choice%"=="3" exit /b 0
echo 无效选择，请重试。
pause
goto menu

:inject
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand JABwACAAPQAgACcAaQBuAGQAZQB4AC4AaAB0AG0AbAAnAAoAaQBmACAAKAAtAG4AbwB0ACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABwACkAKQAgAHsAIABlAHgAaQB0ACAAMQAgAH0ACgAkAGYAdQBsAGwAIAA9ACAAKABSAGUAcwBvAGwAdgBlAC0AUABhAHQAaAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABwACkALgBQAGEAdABoAAoAJAB0ACAAPQAgAFsASQBPAC4ARgBpAGwAZQBdADoAOgBSAGUAYQBkAEEAbABsAFQAZQB4AHQAKAAkAGYAdQBsAGwAKQAKAGkAZgAgACgAJAB0ACAALQBtAGEAdABjAGgAIAAnAGoAcwAvAG0AbwBkAHMALwBNAG8AZABMAG8AYQBkAGUAcgBcAC4AagBzACcAKQAgAHsAIABlAHgAaQB0ACAAMgAgAH0ACgAkAG4AbAAgAD0AIABpAGYAIAAoACQAdAAgAC0AbQBhAHQAYwBoACAAIgBgAHIAYABuACIAKQAgAHsAIAAiAGAAcgBgAG4AIgAgAH0AIABlAGwAcwBlACAAewAgACIAYABuACIAIAB9AAoAJABjAG8AbQBtAGUAbgB0ACAAPQAgACcAIAAgACAAIAA8ACEALQAtACAATQBvAGQATABvAGEAZABlAHIAIADFX3uYKFcgAG0AYQBpAG4ALgBqAHMAIABLTk1SoFJ9jyAALQAtAD4AJwAKACQAcwBjAHIAaQBwAHQAIAA9ACAAJwAgACAAIAAgADwAcwBjAHIAaQBwAHQAIAB0AHkAcABlAD0AIgB0AGUAeAB0AC8AagBhAHYAYQBzAGMAcgBpAHAAdAAiACAAcwByAGMAPQAiAGoAcwAvAG0AbwBkAHMALwBNAG8AZABMAG8AYQBkAGUAcgAuAGoAcwAiAD4APAAvAHMAYwByAGkAcAB0AD4AJwAKACQAaQBuAHMAIAA9ACAAJABjAG8AbQBtAGUAbgB0ACAAKwAgACQAbgBsACAAKwAgACQAcwBjAHIAaQBwAHQAIAArACAAJABuAGwACgAkAG0AIAA9ACAAWwByAGUAZwBlAHgAXQA6ADoATQBhAHQAYwBoACgAJAB0ACwAIAAnACgAPwBtACkAXgBbACAAXAB0AF0AKgA8AHMAYwByAGkAcAB0AFsAXgA+AF0AKgBqAHMALwBtAGEAaQBuAFwALgBqAHMAWwBeAD4AXQAqAD4AXABzACoAPAAvAHMAYwByAGkAcAB0AD4AJwApAAoAaQBmACAAKAAtAG4AbwB0ACAAJABtAC4AUwB1AGMAYwBlAHMAcwApACAAewAgAGUAeABpAHQAIAAzACAAfQAKACQAdAAgAD0AIAAkAHQALgBTAHUAYgBzAHQAcgBpAG4AZwAoADAALAAgACQAbQAuAEkAbgBkAGUAeAApACAAKwAgACQAaQBuAHMAIAArACAAJAB0AC4AUwB1AGIAcwB0AHIAaQBuAGcAKAAkAG0ALgBJAG4AZABlAHgAKQAKAFsASQBPAC4ARgBpAGwAZQBdADoAOgBXAHIAaQB0AGUAQQBsAGwAVABlAHgAdAAoACQAZgB1AGwAbAAsACAAJAB0ACwAIABbAFQAZQB4AHQALgBVAFQARgA4AEUAbgBjAG8AZABpAG4AZwBdADoAOgBuAGUAdwAoACQAZgBhAGwAcwBlACkAKQAKAGUAeABpAHQAIAAwAAoA
set "rc=%errorlevel%"
if "%rc%"=="0" (
  echo [OK] 注入完成。若游戏已打开，请重启游戏。
) else if "%rc%"=="2" (
  echo [i] 管理器已注入，无需重复操作。
) else if "%rc%"=="3" (
  echo [!] 未找到 main.js 脚本标签，注入失败。
) else (
  echo [!] 注入失败，请确计 index.html 存在且可写。
)
pause
goto menu

:remove
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand JABwACAAPQAgACcAaQBuAGQAZQB4AC4AaAB0AG0AbAAnAAoAaQBmACAAKAAtAG4AbwB0ACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABwACkAKQAgAHsAIABlAHgAaQB0ACAAMQAgAH0ACgAkAGYAdQBsAGwAIAA9ACAAKABSAGUAcwBvAGwAdgBlAC0AUABhAHQAaAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABwACkALgBQAGEAdABoAAoAJAB0ACAAPQAgAFsASQBPAC4ARgBpAGwAZQBdADoAOgBSAGUAYQBkAEEAbABsAFQAZQB4AHQAKAAkAGYAdQBsAGwAKQAKAGkAZgAgACgAJAB0ACAALQBuAG8AdABtAGEAdABjAGgAIAAnAGoAcwAvAG0AbwBkAHMALwBNAG8AZABMAG8AYQBkAGUAcgBcAC4AagBzACcAKQAgAHsAIABlAHgAaQB0ACAAMgAgAH0ACgAkAHQAIAA9ACAAWwByAGUAZwBlAHgAXQA6ADoAUgBlAHAAbABhAGMAZQAoACQAdAAsACAAJwAoAD8AbQApAF4AWwAgAFwAdABdACoAPAAhAC0ALQAuACoATQBvAGQATABvAGEAZABlAHIALgAqAC0ALQA+AFsAIABcAHQAXQAqAFwAcgA/AFwAbgAnACwAIAAnACcAKQAKACQAdAAgAD0AIABbAHIAZQBnAGUAeABdADoAOgBSAGUAcABsAGEAYwBlACgAJAB0ACwAIAAnACgAPwBtACkAXgBbACAAXAB0AF0AKgA8AHMAYwByAGkAcAB0AFsAXgA+AF0AKgBqAHMALwBtAG8AZABzAC8ATQBvAGQATABvAGEAZABlAHIAXAAuAGoAcwBbAF4APgBdACoAPgBcAHMAKgA8AC8AcwBjAHIAaQBwAHQAPgBbACAAXAB0AF0AKgBcAHIAPwBcAG4AJwAsACAAJwAnACkACgBbAEkATwAuAEYAaQBsAGUAXQA6ADoAVwByAGkAdABlAEEAbABsAFQAZQB4AHQAKAAkAGYAdQBsAGwALAAgACQAdAAsACAAWwBUAGUAeAB0AC4AVQBUAEYAOABFAG4AYwBvAGQAaQBuAGcAXQA6ADoAbgBlAHcAKAAkAGYAYQBsAHMAZQApACkACgBlAHgAaQB0ACAAMAAKAA==
set "rc=%errorlevel%"
if "%rc%"=="0" (
  echo [OK] 已取消注入，恢复纯凁游戏。
) else if "%rc%"=="2" (
  echo [i] 当前未注入管理器。
) else (
  echo [!] 取消注入失败，请确计 index.html 存在且可写。
)
pause
goto menu

